export const ROUTES = {
  OVERVIEW: "/",
  ACTIVITY: "/activity",
  INBOX: "/inbox",
  CUSTOMERS: "/customers",
  ORDERS: "/orders",
  ORDER_DETAIL: (id: string | number) =>
    `/orders?order=${encodeURIComponent(String(id))}`,
  POS: "/pos",
  SALES_RECOVERY: "/sales-recovery",
  PRODUCTS: "/products",
  INVENTORY: "/inventory",
  STOREFRONT: "/storefront",
  PROMOTIONS: "/promotions",
  PAYMENTS: "/payments",
  PAYMENT_LINKS: "/payments/links",
  INVOICES: "/invoices",
  FINANCES: "/finances",
  FULFILMENT: "/fulfilment",
  RETURNS: "/returns",
  TEAM: "/team",
  ANALYTICS: "/analytics",
  AI_ASSISTANT: "/ai-assistant",
  AUTOMATIONS: "/automations",
  SETTINGS: "/settings",
  BILLING: "/billing",
  SUPPORT: "/support",
} as const;
