export const demoConversations = [
  {
    id: 1,
    customerId: 1,
    name: "Aisha Bello",
    initials: "AB",
    channel: "Instagram",
    preview: "Is the blue dress available?",
    time: "12m",
    unread: 2,
    stage: "Interested",
    productId: 3,
    messages: [
      { from: "customer", text: "Hi, is the blue dress available in my size?" },
      {
        from: "merchant",
        text: "Yes, it is available. I can prepare an order for you.",
      },
      { from: "customer", text: "Great. Please send me a checkout link." },
    ],
  },
  {
    id: 2,
    customerId: 2,
    name: "Chinedu Okafor",
    initials: "CO",
    channel: "WhatsApp",
    preview: "I've made payment",
    time: "31m",
    unread: 0,
    stage: "Checkout Sent",
    productId: 1,
    messages: [
      { from: "customer", text: "I've made payment for the two handbags." },
      {
        from: "merchant",
        text: "Thank you. We will verify the provider event and update your order.",
      },
    ],
  },
  {
    id: 3,
    customerId: 3,
    name: "Zainab Yusuf",
    initials: "ZY",
    channel: "Website",
    preview: "How much is delivery to Ikeja?",
    time: "1h",
    unread: 1,
    stage: "New Enquiry",
    productId: 2,
    messages: [{ from: "customer", text: "How much is delivery to Ikeja?" }],
  },
];
