export const demoConversations = [
  {
    id: 1,
    customerId: 1,
    name: "Aisha Bello",
    initials: "AB",
    channel: "Instagram",
    preview: "Is the blue dress available?",
    time: "12m",
    unread: 2,
    stage: "Interested",
    productId: 3,
    demoReplies: [
      "Thank you! Could you send me the checkout link for the blue dress?",
      "Perfect. Can you deliver it to Lekki tomorrow?",
      "That works for me. Thank you for your help!",
    ],
    messages: [
      { from: "customer", text: "Hi, is the blue dress available in my size?" },
      {
        from: "merchant",
        text: "Yes, it is available. I can prepare an order for you.",
      },
      { from: "customer", text: "Great. Please send me a checkout link." },
    ],
  },
  {
    id: 2,
    customerId: 2,
    name: "Chinedu Okafor",
    initials: "CO",
    channel: "WhatsApp",
    preview: "I've made payment",
    time: "31m",
    unread: 0,
    stage: "Checkout Sent",
    productId: 1,
    demoReplies: [
      "Thanks for checking. Please let me know when my payment is confirmed.",
      "Great. Please pack the two handbags together.",
      "Thank you! I’ll wait for the delivery update.",
    ],
    messages: [
      { from: "customer", text: "I've made payment for the two handbags." },
      {
        from: "merchant",
        text: "Thank you. We will verify the provider event and update your order.",
      },
    ],
  },
  {
    id: 3,
    customerId: 3,
    name: "Zainab Yusuf",
    initials: "ZY",
    channel: "Website",
    preview: "How much is delivery to Ikeja?",
    time: "1h",
    unread: 1,
    stage: "New Enquiry",
    productId: 2,
    demoReplies: [
      "Thanks! I’m in Ikeja. Is store pickup also available?",
      "I’ll choose delivery. Could you prepare a checkout link for the heels?",
      "Lovely, thank you. I’ll review the order details.",
    ],
    messages: [{ from: "customer", text: "How much is delivery to Ikeja?" }],
  },
];
