import {
  Archive,
  ArrowLeft,
  ArrowRight,
  Bell,
  ChartColumn,
  ChevronRight,
  CircleDollarSign,
  ClipboardList,
  Clock,
  CreditCard,
  Ellipsis,
  House,
  Inbox,
  Layers,
  Menu,
  MessageSquare,
  Minus,
  Package,
  Plus,
  Search,
  Settings,
  ShoppingBag,
  Sparkles,
  Store,
  TrendingUp,
  TriangleAlert,
  Users,
  Wallet,
  X,
  type LucideIcon,
} from "lucide-react";
const icons = {
  home: House,
  inbox: Inbox,
  orders: ClipboardList,
  customers: Users,
  products: Layers,
  inventory: Archive,
  store: Store,
  payments: CreditCard,
  reports: ChartColumn,
  settings: Settings,
  search: Search,
  bell: Bell,
  plus: Plus,
  arrow: ArrowRight,
  trend: TrendingUp,
  wallet: Wallet,
  bag: ShoppingBag,
  clock: Clock,
  profit: CircleDollarSign,
  message: MessageSquare,
  package: Package,
  card: CreditCard,
  warning: TriangleAlert,
  chevron: ChevronRight,
  more: Ellipsis,
  sparkles: Sparkles,
  menu: Menu,
  close: X,
  back: ArrowLeft,
  minus: Minus,
} satisfies Record<string, LucideIcon>;
export type IconName = keyof typeof icons;
export function Icon({ name, size = 20 }: { name: IconName; size?: number }) {
  const Component = icons[name];
  return <Component size={size} strokeWidth={1.8} aria-hidden="true" />;
}
